// <auto-generated />
namespace TrackerModuleV1._0.Migrations.PTM
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_upload_file_into_part : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_upload_file_into_part));
        
        string IMigrationMetadata.Id
        {
            get { return "201810290816215_Add_upload_file_into_part"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
